# Generated by Django 6.1 on 2026-08-13 19:17

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='notification_email',
        ),
        migrations.AddField(
            model_name='user',
            name='telegram_username',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Telegram username'),
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(default=datetime.date(2026, 8, 13), max_length=254, unique=True, verbose_name='Email'),
            preserve_default=False,
        ),
    ]
