# Generated by Django 6.1 on 2026-08-13 09:45

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CareLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action_type', models.CharField(choices=[('watering', 'Полив'), ('fertilizing', 'Удобрение'), ('repotting', 'Пересадка'), ('misting', 'Опрыскивание'), ('pruning', 'Обрезка'), ('treatment', 'Лечение'), ('other', 'Другое')], max_length=20, verbose_name='Тип действия')),
                ('date', models.DateField(auto_now_add=True, verbose_name='Дата')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='Примечания')),
            ],
            options={
                'verbose_name': 'Запись в журнале',
                'verbose_name_plural': 'Журнал ухода',
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='Plant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название растения')),
                ('scientific_name', models.CharField(blank=True, max_length=200, null=True, verbose_name='Латинское название')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='plants/', verbose_name='Фото')),
                ('location', models.CharField(blank=True, max_length=100, null=True, verbose_name='Местоположение')),
                ('light_preference', models.CharField(choices=[('direct_sun', 'Прямое солнце'), ('bright_indirect', 'Яркий рассеянный'), ('partial_shade', 'Полутень'), ('shade', 'Тень')], default='bright_indirect', max_length=20, verbose_name='Предпочтение по свету')),
                ('watering_frequency', models.CharField(choices=[('daily', 'Ежедневно'), ('every_2_days', 'Каждые 2 дня'), ('every_3_days', 'Каждые 3 дня'), ('weekly', 'Раз в неделю'), ('every_2_weeks', 'Раз в 2 недели'), ('monthly', 'Раз в месяц'), ('as_needed', 'По мере необходимости')], default='weekly', max_length=20, verbose_name='Частота полива')),
                ('watering_volume', models.PositiveIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(10)], verbose_name='Объём воды (мл)')),
                ('fertilizer_frequency', models.PositiveIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1)], verbose_name='Удобрение (дней)')),
                ('repot_frequency', models.PositiveIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1)], verbose_name='Пересадка (дней)')),
                ('temperature_min', models.FloatField(blank=True, null=True, verbose_name='Минимальная температура °C')),
                ('temperature_max', models.FloatField(blank=True, null=True, verbose_name='Максимальная температура °C')),
                ('humidity_preference', models.PositiveIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(10), django.core.validators.MaxValueValidator(100)], verbose_name='Влажность воздуха %')),
                ('needs_misting', models.BooleanField(default=False, verbose_name='Нуждается в опрыскивании')),
                ('is_toxic', models.BooleanField(default=False, verbose_name='Токсично для животных/детей')),
                ('dormant_period_start', models.DateField(blank=True, null=True, verbose_name='Начало периода покоя')),
                ('dormant_period_end', models.DateField(blank=True, null=True, verbose_name='Конец периода покоя')),
                ('purchased_at', models.DateField(blank=True, null=True, verbose_name='Дата покупки')),
                ('last_watered', models.DateField(blank=True, null=True, verbose_name='Последний полив')),
                ('last_fertilized', models.DateField(blank=True, null=True, verbose_name='Последнее удобрение')),
                ('last_repotted', models.DateField(blank=True, null=True, verbose_name='Последняя пересадка')),
                ('health_status', models.CharField(choices=[('healthy', 'Здоровое'), ('needs_water', 'Нужен полив'), ('needs_fertilizer', 'Нужно удобрение'), ('sick', 'Больное'), ('dying', 'Умирает')], default='healthy', max_length=20, verbose_name='Состояние здоровья')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='Заметки')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Растение',
                'verbose_name_plural': 'Растения',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Reminder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action_type', models.CharField(choices=[('watering', 'Полив'), ('fertilizing', 'Удобрение'), ('repotting', 'Пересадка'), ('misting', 'Опрыскивание'), ('pruning', 'Обрезка'), ('custom', 'Своё действие')], max_length=20, verbose_name='Тип действия')),
                ('custom_action_name', models.CharField(blank=True, max_length=100, null=True, verbose_name='Своё название действия')),
                ('frequency', models.CharField(choices=[('once', 'Разово'), ('daily', 'Ежедневно'), ('weekly', 'Еженедельно'), ('monthly', 'Ежемесячно')], default='once', max_length=20, verbose_name='Периодичность')),
                ('interval_days', models.PositiveIntegerField(default=1, verbose_name='Интервал (дни)')),
                ('reminder_date', models.DateField(verbose_name='Дата напоминания')),
                ('reminder_time', models.TimeField(default='09:00', verbose_name='Время напоминания')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активно')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='Заметки')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Напоминание',
                'verbose_name_plural': 'Напоминания',
                'ordering': ['reminder_date', 'reminder_time'],
            },
        ),
    ]
