# Generated by Django 6.1 on 2026-08-06 13:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plants', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Reminder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action_type', models.CharField(choices=[('watering', 'Полив'), ('fertilizing', 'Удобрение'), ('repotting', 'Пересадка'), ('misting', 'Опрыскивание'), ('pruning', 'Обрезка'), ('custom', 'Своё действие')], max_length=20, verbose_name='Тип действия')),
                ('custom_action_name', models.CharField(blank=True, max_length=100, null=True, verbose_name='Своё название действия')),
                ('frequency', models.CharField(choices=[('once', 'Разово'), ('daily', 'Ежедневно'), ('weekly', 'Еженедельно'), ('monthly', 'Ежемесячно')], default='once', max_length=20, verbose_name='Периодичность')),
                ('interval_days', models.PositiveIntegerField(default=1, verbose_name='Интервал (дни)')),
                ('next_reminder_date', models.DateField(verbose_name='Дата следующего напоминания')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активно')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='Заметки')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('plant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reminders', to='plants.plant', verbose_name='Растение')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reminders', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Напоминание',
                'verbose_name_plural': 'Напоминания',
                'ordering': ['next_reminder_date'],
            },
        ),
    ]
