# Generated by Django 6.1 on 2026-09-01 13:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plants', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='plant',
            name='custom_category',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Пользовательская категория'),
        ),
        migrations.AddField(
            model_name='plant',
            name='is_fruiting',
            field=models.BooleanField(default=False, verbose_name='Плодоносящее'),
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название категории')),
                ('color', models.CharField(default='#3B82F6', max_length=7, verbose_name='Цвет категории (HEX)')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='categories', to=settings.AUTH_USER_MODEL, verbose_name='Владелец')),
            ],
            options={
                'verbose_name': 'Категория',
                'verbose_name_plural': 'Категории',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='PlantPhoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='plants/', verbose_name='Фото')),
                ('caption', models.CharField(blank=True, max_length=255, null=True, verbose_name='Подпись к фото')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Порядок')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('plant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='plants.plant', verbose_name='Фото')),
            ],
            options={
                'verbose_name': 'Фото растения',
                'verbose_name_plural': 'Фото растений',
                'ordering': ['order', 'uploaded_at'],
            },
        ),
    ]
