# Generated by Django 6.1 on 2026-09-10 06:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plants', '0003_plant_custom_category_plant_is_fruiting_category_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='plantphoto',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='plants', to='plants.category', verbose_name='Категория'),
        ),
        migrations.AddField(
            model_name='plantphoto',
            name='custom_category',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Своя категория'),
        ),
        migrations.AddField(
            model_name='plantphoto',
            name='is_fruiting',
            field=models.BooleanField(default=False, verbose_name='Плодоносящее'),
        ),
    ]
