# Generated by Django 6.1 on 2026-08-06 13:49

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plants', '0003_reminder'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='reminder',
            options={'ordering': ['reminder_date', 'reminder_time'], 'verbose_name': 'Напоминание', 'verbose_name_plural': 'Напоминания'},
        ),
        migrations.RemoveField(
            model_name='reminder',
            name='next_reminder_date',
        ),
        migrations.AddField(
            model_name='reminder',
            name='reminder_date',
            field=models.DateField(default=datetime.date(2026, 8, 6), verbose_name='Дата напоминания'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='reminder',
            name='reminder_time',
            field=models.TimeField(default='09:00', verbose_name='Время напоминания'),
        ),
    ]
