# Generated by Django 6.1 on 2026-09-22 19:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plants', '0004_plantphoto_category_plantphoto_custom_category_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='plantphoto',
            name='category',
        ),
        migrations.RemoveField(
            model_name='plantphoto',
            name='custom_category',
        ),
        migrations.RemoveField(
            model_name='plantphoto',
            name='is_fruiting',
        ),
        migrations.AddField(
            model_name='reminder',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='plants', to='plants.category', verbose_name='Категория'),
        ),
        migrations.AddField(
            model_name='reminder',
            name='custom_category',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Пользовательская категория'),
        ),
        migrations.AddField(
            model_name='reminder',
            name='is_fruiting',
            field=models.BooleanField(default=False, verbose_name='Плодоносящее'),
        ),
    ]
