# Generated by Django 6.1 on 2026-09-22 20:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plants', '0005_remove_plantphoto_category_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='plantphoto',
            name='is_main',
            field=models.BooleanField(default=False, verbose_name='Главное фото'),
        ),
    ]
